import { ControllerSection } from './section/controller_section.js';
import { ControllerCards } from './cards/controller_cards.js';
import { ControllerSort } from './sort/controller_sort.js';
import { ControllerModal } from './modal/controller_modal.js';
import { ControllerHeader } from './header/header_controller.js';
import { ControllerButton } from './button/controller_button.js';
import { ControllerSearch } from './search/controller_search.js';
import { ControllerCart } from './cart/controller_cart.js';
import { ControllerPagination } from './pagination/controller_pagination.js';
import { ControllerPopup } from './popup/controller_popup.js';

const controllerHeader = new ControllerHeader();
const controllerSection = new ControllerSection();
const controllerPagination = new ControllerPagination();
const controllerCards = new ControllerCards();
const controllerSort = new ControllerSort();
const controllerModal = new ControllerModal();
const controllerSearch = new ControllerSearch();
const controllerButton = new ControllerButton();
const controllerCart = new ControllerCart();
const controllerPopup = new ControllerPopup();
